basePath: /
definitions:
  domain.Post:
    properties:
      caption:
        type: string
      created_at:
        type: string
      id:
        type: integer
      image_url:
        type: string
      updated_at:
        type: string
      user_id:
        type: integer
    type: object
  domain.User:
    properties:
      created:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      updated:
        type: string
    type: object
  handler.UserLoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  handler.UserRegistrationRequest:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
host: localhost:8084
info:
  contact:
    email: https://wa.me/6285749806571
    name: Elgin Brian Wahyu Bramadhika
    url: https://elginbrian.com
  description: This is a RESTful API for managing posts, users, and authentication
    using JWT. The API is built using the Fiber framework and interacts with a PostgreSQL
    database.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Fiber Starter API
  version: "1.0"
paths:
  /api/auth/login:
    post:
      consumes:
      - application/json
      description: This endpoint allows a user to log in by providing their email
        and password. Upon successful login, a JWT token is generated and returned,
        which can be used for authenticated requests.
      parameters:
      - description: User login details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.UserLoginRequest'
      produces:
      - application/json
      responses: {}
      summary: Logs in an existing user
      tags:
      - auth
  /api/auth/register:
    post:
      consumes:
      - application/json
      description: This endpoint allows users to create a new account by providing
        a username, email, and password. The registration data is validated, and upon
        successful registration, a success message is returned.
      parameters:
      - description: User registration details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.UserRegistrationRequest'
      produces:
      - application/json
      responses: {}
      summary: Registers a new user
      tags:
      - auth
  /api/posts:
    get:
      description: Retrieves all posts, including the user who created them, the caption,
        image URL, and timestamps.
      produces:
      - application/json
      responses: {}
      summary: Get all posts
      tags:
      - posts
    post:
      consumes:
      - multipart/form-data
      description: Creates a new post with an optional image. The caption is required.
        If an image is provided, it will be uploaded to the server, and the URL will
        be returned in the response.
      parameters:
      - description: Post caption
        in: formData
        name: caption
        required: true
        type: string
      - description: Post image (optional)
        in: formData
        name: image
        type: file
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Create a new post
      tags:
      - posts
  /api/posts/{id}:
    delete:
      description: Deletes a post by its ID. Only the creator of the post is authorized
        to delete it.
      parameters:
      - description: Post ID
        in: path
        name: id
        required: true
        type: integer
      responses: {}
      security:
      - BearerAuth: []
      summary: Delete a post
      tags:
      - posts
    get:
      description: Retrieves a specific post by its ID, including its caption, image
        URL, and timestamps.
      parameters:
      - description: Post ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: Get a post by ID
      tags:
      - posts
    put:
      consumes:
      - application/json
      description: Updates the details of a post (caption and/or image). Only the
        creator of the post is allowed to update it.
      parameters:
      - description: Post ID
        in: path
        name: id
        required: true
        type: integer
      - description: Updated post details
        in: body
        name: post
        required: true
        schema:
          $ref: '#/definitions/domain.Post'
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Update an existing post
      tags:
      - posts
  /api/users:
    get:
      description: Fetches all user records from the database and returns them with
        timestamps for creation and update.
      produces:
      - application/json
      responses: {}
      summary: Retrieve a list of all users
      tags:
      - users
    post:
      consumes:
      - application/json
      description: Accepts user details from the request body, validates the input,
        and creates a new user in the database. Returns the created user's details
        along with timestamps.
      parameters:
      - description: User details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/domain.User'
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Create a new user record
      tags:
      - users
  /api/users/{id}:
    delete:
      description: Accepts the user ID as a path parameter and deletes the user record
        from the database. Returns a success message upon deletion.
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      responses: {}
      security:
      - BearerAuth: []
      summary: Delete a user record by ID
      tags:
      - users
    get:
      description: Fetches a specific user record from the database by the provided
        ID and returns the user's details, including timestamps.
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: Retrieve user details by user ID
      tags:
      - users
    put:
      consumes:
      - application/json
      description: Accepts the user ID as a path parameter, along with updated user
        data in the request body, and updates the user record in the database. Returns
        the updated user's details with timestamps.
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: Updated user details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/domain.User'
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Update an existing user's details
      tags:
      - users
swagger: "2.0"
